import './globals.css'
import localFont from "next/font/local"

export const metadata = {
  title: 'Anything you like',
  description: 'Generated by create next app',
}

const myFont = localFont({
  src: "../public/fonts/NanumSquareRoundB.ttf",
  display: "swap",
})
export default async function RootLayout({ children }) {
  // let session = await getServerSession(authOptions)
  return (
    <html lang="ko" className={myFont.className}>
      <body>
        {children}
      </body>
    </html>
  )
}

